//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adodataobjectsdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string job_name { get; set; }
        public Nullable<int> manager_id { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<int> dep_id { get; set; }
    
        public virtual department department { get; set; }
    }
}
