//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adodataobjectsdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_grade
    {
        public int grade { get; set; }
        public Nullable<int> min_salary { get; set; }
        public Nullable<int> max_salary { get; set; }
    }
}
