//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvchandson14_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public string name { get; set; }
        public int skill { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
    }
}
